all_tv_shows = ["Boy Meets World",
                "Everybody Hates Chris",
                "Breaking Bad",
                "Arrested Development",
                "Suits",
                "Malcolm in the Middle",
                "Frasier",
                "The Middle",
                "Home Improvement",
                "Cheers",
                "The Goldbergs",
                "Friends",
                "Stranger Things",
                "Parks And Recreation",
                "New Girl",
                "3rd Rock from the Sun",
                "The Fresh Prince of Bel-Air",
                "Schitt's Creek",
                "Gilmore Girls",
                "The Good Place",
                "Everybody Loves Raymond",
                "The Office",
                "How I Met Your Mother",
                "Scrubs",
                "Seinfeld",
                "Derry Girls",
                "Lucifer",
                "Monk",
                "Modern Family",
                "The Golden Girls",
                "Brooklyn Nine-Nine"
                ]