# Generated by Django 4.2.4 on 2023-10-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(null=True)),
                ('widget_family', models.TextField(null=True)),
                ('device_type', models.TextField(null=True)),
                ('os_version', models.CharField(max_length=20, null=True)),
                ('ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('city', models.CharField(default='city', max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('PickupCount', models.IntegerField()),
                ('NasaCount', models.IntegerField()),
                ('FactofTheDayCount', models.IntegerField()),
                ('SpeedTestCount', models.IntegerField()),
                ('TvShowCount', models.IntegerField()),
                ('WordOftheDayCount', models.IntegerField()),
            ],
        ),
    ]
