# Generated by Django 4.2.4 on 2023-10-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceanalytics',
            name='FactofTheDayCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceanalytics',
            name='NasaCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceanalytics',
            name='PickupCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceanalytics',
            name='SpeedTestCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceanalytics',
            name='TvShowCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceanalytics',
            name='WordOftheDayCount',
            field=models.IntegerField(null=True),
        ),
    ]
