# Generated by Django 4.2.4 on 2023-08-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.TextField(max_length=500)),
                ('character', models.TextField(max_length=200)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
