# Generated by Django 4.2.4 on 2023-08-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.TextField(max_length=400, null=True)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('ip_country', models.CharField(max_length=200)),
                ('ip_city', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('url', models.BinaryField(null=True)),
            ],
        ),
    ]
