# Generated by Django 4.2.4 on 2023-08-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest', '0003_alter_speedtest_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtest',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
