# Generated by Django 4.2.4 on 2023-08-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest', '0004_alter_speedtest_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speedtest',
            old_name='speed',
            new_name='BinaryUrl',
        ),
        migrations.RenameField(
            model_name='speedtest',
            old_name='datetime',
            new_name='DateTime',
        ),
        migrations.AddField(
            model_name='speedtest',
            name='DeviceNameModel',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='speedtest',
            name='Speed',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='speedtest',
            name='SystemVersion',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
