# Generated by Django 4.2.4 on 2023-08-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest', '0005_rename_speed_speedtest_binaryurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedtest',
            name='ConnectionType',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speedtest',
            name='DeviceId',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speedtest',
            name='ISP',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speedtest',
            name='Ping',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speedtest',
            name='Server',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speedtest',
            name='Upload_Speed',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speedtest',
            name='WidgetFamily',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
