# Generated by Django 4.2.4 on 2023-10-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordOfTheDayinHindi', models.TextField(max_length=50)),
                ('wordOfTheDayinEnglish', models.TextField(max_length=50)),
                ('wordOfTheDayinEnglish_Usage_Example', models.TextField(max_length=2000)),
                ('wordOfTheDayinHindi_Usage_Example', models.TextField(max_length=2000)),
                ('date', models.DateField()),
            ],
        ),
    ]
