# Generated by Django 4.2.4 on 2023-09-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasaapod',
            name='hd_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='nasaapod',
            name='standard_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
