# Generated by Django 4.2.4 on 2023-09-04 08:55

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_nasaapod_hd_image_nasaapod_standard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasaapod',
            name='hd_image',
            field=models.ImageField(null=True, upload_to=base.models.upload_image),
        ),
        migrations.AlterField(
            model_name='nasaapod',
            name='standard_image',
            field=models.ImageField(null=True, upload_to=base.models.upload_image),
        ),
    ]
