# Generated by Django 4.2.4 on 2023-09-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbers_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='date',
        ),
        migrations.RemoveField(
            model_name='number',
            name='month',
        ),
    ]
