# Generated by Django 4.2.4 on 2023-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbers_api', '0002_remove_number_date_remove_number_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='date',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='number',
            name='month',
            field=models.IntegerField(default=1),
        ),
    ]
