# Generated by Django 4.2.4 on 2023-09-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbers_api', '0003_number_date_number_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='number',
            name='month',
            field=models.IntegerField(),
        ),
    ]
